name: 🐛 Bug report
description: Create a report to help us improve
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Please make sure you have read the docs and are using the latest version of Knip. Use common sense and provide the necessary information that helps me or others to help you.

        A minimal reproduction is required: only the code and configuration required to demonstrate the issue.

        Please make sure you've read https://knip.dev/guides/issue-reproduction.
  - type: input
    id: reproduction
    attributes:
      label: Reproduction url
      description: Please link to the location of the issue reproduction
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description of the issue
      description: What happened, and what would you expect to happen?
    validations:
      required: true
