name: 🧩 Everything Else
description: Discuss anything related to Knip
title: '🧩 <TITLE>'
labels: ['discussion']
body:
  - type: markdown
    attributes:
      value: |
        <!--
          Feel free to discuss anything related to Knip.
          Just saying, there's also a Discord channel: https://discord.gg/r5uXTtbTpc
        -->
