name: Tests (against typescript@latest in Node.js v20)

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '**'
    tags:
      - '!**'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ubuntu/Node v20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -D typescript@latest @types/node@20
      - name: Build knip
        run: npm run build
        working-directory: packages/knip
      - name: QA (format, lint, organize imports)
        run: npm run ci
      - name: Test knip
        run: npm run test
        working-directory: packages/knip
      - name: Run knip
        run: npx knip
      - name: Run knip --production --strict
        run: npx knip --production --strict
