name: Tests (against typescript@latest)

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '**'
    tags:
      - '!**'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ubuntu/Node v20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install typescript@latest
      - run: npm run build --workspace packages/knip
      - run: npx knip
      - run: npx knip --production --strict
      - run: npm test --workspaces --if-present
